name: Test & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     dotnet-version: [ '3.1.x', '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        # with:
        #   dotnet-version: ${{ matrix.dotnet-version }}
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore --locked-mode
      
      - name: Build
        run: dotnet build --verbosity minimal
      
      - name: Test with the dotnet CLI
        run: dotnet test --no-build --logger "trx;LogFileName=pw-test-results.trx"
      
      - name: Report test results
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226 # v1.6.0
        if: always()
        with:
          name: Test Results
          path: "**/*-test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
      
      - name: Check format
        run: dotnet format --verify-no-changes